import type { Event } from './types'

export const events: Event[] = [
  // ── WNBA ──────────────────────────────────────────────────────────────────
  {
    id: 'wnba-1',
    sport: 'WNBA',
    title: 'NY Liberty vs Chicago Sky',
    venue: 'Barclays Center',
    city: 'Brooklyn',
    state: 'NY',
    date: '2026-05-25',
    time: '1:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 38, url: '#' },
      { market: 'SeatGeek', minPrice: 34, url: '#' },
      { market: 'StubHub', minPrice: 41, url: '#' },
    ],
  },
  {
    id: 'wnba-2',
    sport: 'WNBA',
    title: 'Seattle Storm vs Phoenix Mercury',
    venue: 'Climate Pledge Arena',
    city: 'Seattle',
    state: 'WA',
    date: '2026-05-30',
    time: '7:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 29, url: '#' },
      { market: 'SeatGeek', minPrice: 27, url: '#' },
      { market: 'Vivid Seats', minPrice: 32, url: '#' },
    ],
  },
  {
    id: 'wnba-3',
    sport: 'WNBA',
    title: 'Indiana Fever vs Atlanta Dream',
    subtitle: 'Caitlin Clark Homecoming',
    venue: 'Gainbridge Fieldhouse',
    city: 'Indianapolis',
    state: 'IN',
    date: '2026-06-01',
    time: '7:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 72, url: '#' },
      { market: 'SeatGeek', minPrice: 65, url: '#' },
      { market: 'StubHub', minPrice: 78, url: '#' },
      { market: 'Vivid Seats', minPrice: 69, url: '#' },
    ],
  },
  {
    id: 'wnba-4',
    sport: 'WNBA',
    title: 'Las Vegas Aces vs Dallas Wings',
    venue: 'Michelob ULTRA Arena',
    city: 'Las Vegas',
    state: 'NV',
    date: '2026-06-05',
    time: '9:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 44, url: '#' },
      { market: 'SeatGeek', minPrice: 39, url: '#' },
    ],
  },
  {
    id: 'wnba-5',
    sport: 'WNBA',
    title: 'Minnesota Lynx vs Connecticut Sun',
    venue: 'Target Center',
    city: 'Minneapolis',
    state: 'MN',
    date: '2026-06-12',
    time: '7:30 PM',
    markets: [
      { market: 'SeatGeek', minPrice: 22, url: '#' },
      { market: 'StubHub', minPrice: 25, url: '#' },
      { market: 'Vivid Seats', minPrice: 20, url: '#' },
    ],
  },
  {
    id: 'wnba-6',
    sport: 'WNBA',
    title: 'Los Angeles Sparks vs Washington Mystics',
    venue: 'Crypto.com Arena',
    city: 'Los Angeles',
    state: 'CA',
    date: '2026-06-18',
    time: '7:30 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 31, url: '#' },
      { market: 'SeatGeek', minPrice: 28, url: '#' },
      { market: 'StubHub', minPrice: 35, url: '#' },
    ],
  },

  // ── NWSL ──────────────────────────────────────────────────────────────────
  {
    id: 'nwsl-1',
    sport: 'NWSL',
    title: 'Portland Thorns vs Seattle Reign',
    subtitle: 'Rose City Derby',
    venue: 'Providence Park',
    city: 'Portland',
    state: 'OR',
    date: '2026-05-24',
    time: '5:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 28, url: '#' },
      { market: 'SeatGeek', minPrice: 24, url: '#' },
      { market: 'StubHub', minPrice: 31, url: '#' },
    ],
  },
  {
    id: 'nwsl-2',
    sport: 'NWSL',
    title: 'Kansas City Current vs Angel City FC',
    venue: 'CPKC Stadium',
    city: 'Kansas City',
    state: 'MO',
    date: '2026-05-31',
    time: '2:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 22, url: '#' },
      { market: 'SeatGeek', minPrice: 19, url: '#' },
    ],
  },
  {
    id: 'nwsl-3',
    sport: 'NWSL',
    title: 'Washington Spirit vs NJ/NY Gotham FC',
    venue: 'Audi Field',
    city: 'Washington',
    state: 'DC',
    date: '2026-06-07',
    time: '4:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 18, url: '#' },
      { market: 'SeatGeek', minPrice: 16, url: '#' },
      { market: 'Vivid Seats', minPrice: 21, url: '#' },
    ],
  },
  {
    id: 'nwsl-4',
    sport: 'NWSL',
    title: 'Chicago Red Stars vs Houston Dash',
    venue: 'SeatGeek Stadium',
    city: 'Bridgeview',
    state: 'IL',
    date: '2026-06-14',
    time: '3:00 PM',
    markets: [
      { market: 'SeatGeek', minPrice: 15, url: '#' },
      { market: 'StubHub', minPrice: 18, url: '#' },
    ],
  },
  {
    id: 'nwsl-5',
    sport: 'NWSL',
    title: 'San Diego Wave vs Orlando Pride',
    venue: 'Snapdragon Stadium',
    city: 'San Diego',
    state: 'CA',
    date: '2026-06-20',
    time: '7:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 25, url: '#' },
      { market: 'SeatGeek', minPrice: 22, url: '#' },
      { market: 'StubHub', minPrice: 28, url: '#' },
    ],
  },

  // ── Tennis ────────────────────────────────────────────────────────────────
  {
    id: 'tennis-1',
    sport: 'Tennis',
    title: 'French Open',
    subtitle: "Women's Singles Final",
    venue: 'Roland Garros',
    city: 'Paris',
    state: 'France',
    date: '2026-06-06',
    time: '3:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 145, url: '#' },
      { market: 'StubHub', minPrice: 198, url: '#' },
      { market: 'Vivid Seats', minPrice: 172, url: '#' },
    ],
  },
  {
    id: 'tennis-2',
    sport: 'Tennis',
    title: 'Wimbledon',
    subtitle: "Women's Singles Semi-Finals",
    venue: 'All England Club',
    city: 'London',
    state: 'UK',
    date: '2026-07-09',
    time: '12:00 PM',
    markets: [
      { market: 'StubHub', minPrice: 225, url: '#' },
      { market: 'Vivid Seats', minPrice: 249, url: '#' },
    ],
  },
  {
    id: 'tennis-3',
    sport: 'Tennis',
    title: 'US Open',
    subtitle: "Women's Singles Final",
    venue: 'Arthur Ashe Stadium',
    city: 'New York',
    state: 'NY',
    date: '2026-09-12',
    time: '4:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 185, url: '#' },
      { market: 'SeatGeek', minPrice: 162, url: '#' },
      { market: 'StubHub', minPrice: 210, url: '#' },
      { market: 'Vivid Seats', minPrice: 178, url: '#' },
    ],
  },
  {
    id: 'tennis-4',
    sport: 'Tennis',
    title: 'Eastbourne International',
    subtitle: "Women's Singles",
    venue: 'Devonshire Park',
    city: 'Eastbourne',
    state: 'UK',
    date: '2026-06-22',
    time: '11:00 AM',
    markets: [
      { market: 'Ticketmaster', minPrice: 48, url: '#' },
      { market: 'SeatGeek', minPrice: 42, url: '#' },
    ],
  },

  // ── Golf ──────────────────────────────────────────────────────────────────
  {
    id: 'golf-1',
    sport: 'Golf',
    title: 'KPMG Women\'s PGA Championship',
    subtitle: 'Round 1–4 Grounds Pass',
    venue: 'Sahalee Country Club',
    city: 'Sammamish',
    state: 'WA',
    date: '2026-06-18',
    time: '7:00 AM',
    markets: [
      { market: 'Ticketmaster', minPrice: 65, url: '#' },
      { market: 'SeatGeek', minPrice: 58, url: '#' },
    ],
  },
  {
    id: 'golf-2',
    sport: 'Golf',
    title: 'U.S. Women\'s Open',
    subtitle: 'Weekend Grounds Pass',
    venue: 'Lancaster Country Club',
    city: 'Lancaster',
    state: 'PA',
    date: '2026-07-11',
    time: '7:30 AM',
    markets: [
      { market: 'Ticketmaster', minPrice: 95, url: '#' },
      { market: 'StubHub', minPrice: 112, url: '#' },
      { market: 'Vivid Seats', minPrice: 88, url: '#' },
    ],
  },
  {
    id: 'golf-3',
    sport: 'Golf',
    title: 'Chevron Championship',
    subtitle: 'Final Round',
    venue: 'The Club at Carlton Woods',
    city: 'The Woodlands',
    state: 'TX',
    date: '2026-06-28',
    time: '9:00 AM',
    markets: [
      { market: 'Ticketmaster', minPrice: 72, url: '#' },
      { market: 'SeatGeek', minPrice: 65, url: '#' },
      { market: 'StubHub', minPrice: 80, url: '#' },
    ],
  },

  // ── College ───────────────────────────────────────────────────────────────
  {
    id: 'college-1',
    sport: 'College',
    title: 'NCAA Softball College World Series',
    subtitle: 'Championship Round',
    venue: 'USA Softball Hall of Fame Stadium',
    city: 'Oklahoma City',
    state: 'OK',
    date: '2026-06-08',
    time: '7:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 35, url: '#' },
      { market: 'SeatGeek', minPrice: 30, url: '#' },
      { market: 'StubHub', minPrice: 42, url: '#' },
    ],
  },
  {
    id: 'college-2',
    sport: 'College',
    title: "NCAA Women's Basketball Final Four",
    venue: 'Gainbridge Fieldhouse',
    city: 'Indianapolis',
    state: 'IN',
    date: '2026-06-25',
    time: '7:30 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 88, url: '#' },
      { market: 'SeatGeek', minPrice: 79, url: '#' },
      { market: 'StubHub', minPrice: 95, url: '#' },
      { market: 'Vivid Seats', minPrice: 82, url: '#' },
    ],
  },
  {
    id: 'college-3',
    sport: 'College',
    title: "NCAA Women's Soccer College Cup",
    venue: 'WakeMed Soccer Park',
    city: 'Cary',
    state: 'NC',
    date: '2026-12-04',
    time: '4:00 PM',
    markets: [
      { market: 'Ticketmaster', minPrice: 28, url: '#' },
      { market: 'SeatGeek', minPrice: 24, url: '#' },
    ],
  },
]

export const SPORTS = ['WNBA', 'NWSL', 'PWHL', 'Tennis', 'Golf', 'College'] as const
